-- 数据生命周期表
CREATE TABLE IF NOT EXISTS `data_lifecycle` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `data_asset_id` BIGINT NOT NULL COMMENT '数据资产ID',
    `data_asset_name` VARCHAR(200) NOT NULL COMMENT '数据资产名称',
    `data_asset_type` VARCHAR(50) NOT NULL COMMENT '数据资产类型',
    `current_stage` VARCHAR(50) NOT NULL COMMENT '当前生命周期阶段',
    `previous_stage` VARCHAR(50) NULL COMMENT '上一个生命周期阶段',
    `stage_changed_at` DATETIME NULL COMMENT '阶段变更时间',
    `change_reason` VARCHAR(500) NULL COMMENT '阶段变更原因',
    `expected_archive_time` DATETIME NULL COMMENT '预计归档时间',
    `expected_destroy_time` DATETIME NULL COMMENT '预计销毁时间',
    `actual_archive_time` DATETIME NULL COMMENT '实际归档时间',
    `actual_destroy_time` DATETIME NULL COMMENT '实际销毁时间',
    `policy_id` BIGINT NULL COMMENT '生命周期策略ID',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `status` INT NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
    `remark` VARCHAR(500) NULL COMMENT '备注',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` VARCHAR(100) NULL COMMENT '创建人',
    `update_by` VARCHAR(100) NULL COMMENT '更新人',
    `deleted` INT NOT NULL DEFAULT 0 COMMENT '删除标记：0-未删除，1-已删除',
    PRIMARY KEY (`id`),
    INDEX idx_data_asset_id (`data_asset_id`),
    INDEX idx_current_stage (`current_stage`),
    INDEX idx_tenant_id (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据生命周期表';

-- 生命周期阶段配置表
CREATE TABLE IF NOT EXISTS `lifecycle_stage` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `stage_name` VARCHAR(100) NOT NULL COMMENT '阶段名称',
    `stage_code` VARCHAR(50) NOT NULL COMMENT '阶段编码',
    `stage_description` VARCHAR(500) NULL COMMENT '阶段描述',
    `enabled` INT NOT NULL DEFAULT 1 COMMENT '是否启用：0-禁用，1-启用',
    `next_stage_code` VARCHAR(50) NULL COMMENT '下一阶段编码',
    `previous_stage_code` VARCHAR(50) NULL COMMENT '上一阶段编码',
    `duration_days` INT NULL COMMENT '阶段持续时间（天）',
084    `warning_threshold` INT NULL COMMENT '预警阈值（百分比）',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序序号',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` VARCHAR(100) NULL COMMENT '创建人',
    `update_by` VARCHAR(100) NULL COMMENT '更新人',
    `deleted` INT NOT NULL DEFAULT 0 COMMENT '删除标记：0-未删除，1-已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY uk_stage_code (`stage_code`, `tenant_id`),
    INDEX idx_enabled (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='生命周期阶段配置表';

-- 生命周期策略表
CREATE TABLE IF NOT EXISTS `lifecycle_policy` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `policy_name` VARCHAR(100) NOT NULL COMMENT '策略名称',
    `policy_code` VARCHAR(50) NOT NULL COMMENT '策略编码',
    `policy_description` VARCHAR(500) NULL COMMENT '策略描述',
    `data_asset_type` VARCHAR(50) NOT NULL COMMENT '数据资产类型',
    `archive_strategy` INT NOT NULL DEFAULT 0 COMMENT '归档策略：0-不归档，1-自动归档，2-手动归档',
    `archive_threshold_days` INT NULL COMMENT '归档天数阈值',
    `destroy_strategy` INT NOT NULL DEFAULT 0 COMMENT '销毁策略：0-不销毁，1-自动销毁，2-手动销毁',
    `destroy_threshold_days` INT NULL COMMENT '销毁天数阈值',
    `cleanup_strategy` INT NOT NULL DEFAULT 0 COMMENT '清理策略：0-不清理，1-自动清理，2-手动清理',
    `cleanup_threshold_days` INT NULL COMMENT '清理天数阈值',
    `enabled` INT NOT NULL DEFAULT 1 COMMENT '是否启用：0-禁用，1-启用',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `remark` VARCHAR(500) NULL COMMENT '备注',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` VARCHAR(100) NULL COMMENT '创建人',
    `update_by` VARCHAR(100) NULL COMMENT '更新人',
    `deleted` INT NOT NULL DEFAULT 0 COMMENT '删除标记：0-未删除，1-已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY uk_policy_code (`policy_code`, `tenant_id`),
    INDEX idx_data_asset_type (`data_asset_type`),
    INDEX idx_enabled (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='生命周期策略表';

-- 归档记录表
CREATE TABLE IF NOT EXISTS `archive_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `lifecycle_id` BIGINT NOT NULL COMMENT '数据生命周期ID',
    `data_asset_id` BIGINT NOT NULL COMMENT '数据资产ID',
    `data_asset_name` VARCHAR(200) NOT NULL COMMENT '数据资产名称',
    `archive_type` INT NOT NULL COMMENT '归档类型：0-自动归档，1-手动归档',
    `archive_status` INT NOT NULL DEFAULT 1 COMMENT '归档状态：0-归档中，1-已归档，2-归档失败',
    `archive_time` DATETIME NOT NULL COMMENT '归档时间',
    `archive_operator` VARCHAR(100) NULL COMMENT '归档操作人',
    `archive_storage_path` VARCHAR(500) NULL COMMENT '归档存储路径',
    `archive_storage_type` INT NOT NULL DEFAULT 1 COMMENT '归档存储类型：0-本地存储，1-对象存储，2-云存储',
    `archive_file_size` BIGINT NULL COMMENT '归档文件大小（字节）',
    `archive_remark` VARCHAR(500) NULL COMMENT '归档备注',
    `restore_status` INT NOT NULL DEFAULT 0 COMMENT '还原状态：0-未还原，1-已还原',
    `restore_time` DATETIME NULL COMMENT '还原时间',
    `restore_operator` VARCHAR(100) NULL COMMENT '还原操作人',
    `restore_remark` VARCHAR(500) NULL COMMENT '还原备注',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` VARCHAR(100) NULL COMMENT '创建人',
    `update_by` VARCHAR(100) NULL COMMENT '更新人',
    `deleted` INT NOT NULL DEFAULT 0 COMMENT '删除标记：0-未删除，1-已删除',
    PRIMARY KEY (`id`),
    INDEX idx_data_asset_id (`data_asset_id`),
    INDEX idx_archive_status (`archive_status`),
    INDEX idx_restore_status (`restore_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='归档记录表';