CREATE DATABASE IF NOT EXISTS edams_ethics CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE edams_ethics;

CREATE TABLE IF NOT EXISTS ethics_framework (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    framework_code VARCHAR(64) NOT NULL UNIQUE,
    framework_name VARCHAR(128) NOT NULL,
    description TEXT,
    principles JSON,
    risk_threshold VARCHAR(32),
    version INT NOT NULL DEFAULT 1,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    creator VARCHAR(64),
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64),
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    tags VARCHAR(512),
    category VARCHAR(64),
    source VARCHAR(128),
    INDEX idx_framework_code (framework_code),
    INDEX idx_framework_name (framework_name),
    INDEX idx_framework_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ethics_assessment (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    assessment_code VARCHAR(64) NOT NULL UNIQUE,
    asset_id VARCHAR(64) NOT NULL,
    asset_name VARCHAR(256),
    framework_id BIGINT,
    framework_name VARCHAR(128),
    transparency_score VARCHAR(32),
    transparency_value DECIMAL(5,2),
    fairness_score VARCHAR(32),
    fairness_value DECIMAL(5,2),
    accountability_score VARCHAR(32),
    accountability_value DECIMAL(5,2),
    privacy_score VARCHAR(32),
    privacy_value DECIMAL(5,2),
    overall_score DECIMAL(5,2),
    overall_risk VARCHAR(32),
    recommendations JSON,
    concerns JSON,
    methodology VARCHAR(32) DEFAULT 'AUTOMATED',
    assessor VARCHAR(64),
    assessed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at DATETIME,
    status VARCHAR(32) DEFAULT 'COMPLETED',
    notes TEXT,
    INDEX idx_assessment_asset (asset_id),
    INDEX idx_assessment_framework (framework_id),
    INDEX idx_assessment_risk (overall_risk),
    INDEX idx_assessment_time (assessed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ethics_review (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    review_code VARCHAR(64) NOT NULL UNIQUE,
    title VARCHAR(256) NOT NULL,
    description TEXT,
    asset_id VARCHAR(64) NOT NULL,
    asset_name VARCHAR(256),
    risk_level VARCHAR(32),
    review_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    priority VARCHAR(16) DEFAULT 'MEDIUM',
    requester VARCHAR(64),
    requester_department VARCHAR(128),
    reviewer VARCHAR(64),
    reviewer_department VARCHAR(128),
    approver VARCHAR(64),
    submitted_at DATETIME,
    reviewed_at DATETIME,
    approved_at DATETIME,
    executed_at DATETIME,
    expiry_date DATETIME,
    review_comments JSON,
    approval_comments TEXT,
    rejection_reason TEXT,
    conditions JSON,
    supporting_docs VARCHAR(1024),
    justification TEXT,
    alternative_analysis TEXT,
    stakeholder_impact TEXT,
    mitigation_plan TEXT,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 1,
    INDEX idx_review_asset (asset_id),
    INDEX idx_review_status (status),
    INDEX idx_review_type (review_type),
    INDEX idx_review_priority (priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS social_impact_report (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    report_code VARCHAR(64) NOT NULL UNIQUE,
    asset_id VARCHAR(64) NOT NULL,
    asset_name VARCHAR(256),
    report_date DATETIME NOT NULL,
    report_period VARCHAR(64),
    overall_risk VARCHAR(32),
    overall_impact_score DECIMAL(5,2),
    data_usage_impact_score DECIMAL(5,2),
    stakeholder_score DECIMAL(5,2),
    social_value_score DECIMAL(5,2),
    community_benefit_score DECIMAL(5,2),
    data_usage_analysis TEXT,
    stakeholder_analysis TEXT,
    impact_assessment TEXT,
    positive_impacts JSON,
    negative_impacts JSON,
    affected_stakeholders JSON,
    recommendations JSON,
    data_governance_score DECIMAL(5,2),
    transparency_score DECIMAL(5,2),
    accountability_score DECIMAL(5,2),
    compliance_score DECIMAL(5,2),
    analyst VARCHAR(64),
    status VARCHAR(32) DEFAULT 'DRAFT',
    approval_status VARCHAR(32) DEFAULT 'PENDING',
    approved_by VARCHAR(64),
    approved_at DATETIME,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes TEXT,
    INDEX idx_social_asset (asset_id),
    INDEX idx_social_report_time (report_date),
    INDEX idx_social_risk (overall_risk)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
